[package]
name = "sys_gvl"
version = "0.1.0"
edition = "2021"
authors = ["yuuji.yaginuma <yuuji.yaginuma@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
lucchetto = "0.4.0"
magnus = { version = "^0.7.1" }
